Repository appuio/terraform-openshift4-cloudscale, pull requests merged in 2021-09, with the labels that each got.

#32 Fix hieradata_mr_url error when lb_count is 0
  lb.tf
  outputs.tf
Labels: bug

#33 Factor out loadbalancer module
  bootstrap.tf
  files/commit-hieradata.sh
  files/register-server.sh
  lb.tf
  main.tf
  outputs.tf
  templates/hieradata.yaml.tmpl
Labels: breaking

#29 Allow using an existing subnet
  bootstrap.tf
  infra.tf
  lb.tf
  main.tf
  master.tf
  outputs.tf
  variables.tf
  worker.tf
Labels: breaking

#34 Make `subnet_uuid` optional
  variables.tf
Labels: change

#35 Add variable privnet_uuid
  lb.tf
  main.tf
  variables.tf
  worker.tf
Labels: change
